let map=null,marker=null,routeLine=null,savedRouteLine=null,watchId=null,timerId=null;
let points=[],startedAt=0,distanceMeters=0,maxSpeed=0,followingRoute=null,lastPosition=null;
let settings={autoCenter:true,highAccuracy:true,trackingInterval:1000,autoSave:true,unit:'km'};
const $=id=>document.getElementById(id),home=$('homeScreen'),ride=$('rideScreen'),routesScreen=$('routesScreen');
function show(s){[home,ride,routesScreen].forEach(x=>x.classList.add('hidden'));s.classList.remove('hidden');if(s===ride&&map)setTimeout(()=>map.invalidateSize(),100)}
function getRoutes(){try{return JSON.parse(localStorage.getItem('e-track-routes')||'[]')}catch{return[]}}
function setRoutes(r){localStorage.setItem('e-track-routes',JSON.stringify(r))}
function loadSettings(){try{settings={...settings,...JSON.parse(localStorage.getItem('e-track-settings')||'{}')}}catch{}}
function saveSettings(){localStorage.setItem('e-track-settings',JSON.stringify(settings))}
function dist(a,b){const R=6371000,p=Math.PI/180,la=a[0]*p,lb=b[0]*p,dl=(b[0]-a[0])*p,do_=(b[1]-a[1])*p,x=Math.sin(dl/2)**2+Math.cos(la)*Math.cos(lb)*Math.sin(do_/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function fmt(ms){let t=Math.max(0,Math.floor(ms/1000));return [Math.floor(t/3600),Math.floor(t%3600/60),t%60].map(v=>String(v).padStart(2,'0')).join(':')}
function gpsSpeed(p){return p.coords.speed!=null&&p.coords.speed>=0?p.coords.speed*3.6:0}
function reset(){points=[];distanceMeters=0;maxSpeed=0;lastPosition=null;$('time').textContent='00:00:00';$('distance').textContent='0.00 km';$('accuracy').textContent='…';$('speed').textContent='0.0 km/h';$('avgSpeed').textContent='0.0 km/h';$('maxSpeed').textContent='0.0 km/h';$('routeStatus').classList.add('hidden')}
function initMap(lat,lon){if(!map){map=L.map('map',{zoomControl:false,preferCanvas:true,zoomAnimation:false}).setView([lat,lon],17);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);routeLine=L.polyline([],{color:'#ff3030',weight:5,opacity:.9}).addTo(map);const locate=L.control({position:'topright'});locate.onAdd=function(){const b=L.DomUtil.create('button','map-locate');b.type='button';b.title='Zu meinem Standort';b.setAttribute('aria-label','Zu meinem Standort');b.textContent='◎';L.DomEvent.disableClickPropagation(b);L.DomEvent.on(b,'click',centerOnUser);return b};locate.addTo(map)}}
function setMarker(lat,lon){if(marker)map.removeLayer(marker);marker=L.circleMarker([lat,lon],{radius:8,color:'#fff',weight:3,fillColor:'#ff3030',fillOpacity:1}).addTo(map)}
function validPosition(p){return p&&p.coords&&Number.isFinite(p.coords.latitude)&&Number.isFinite(p.coords.longitude)}
function update(p){if(!validPosition(p))return;const cur=[p.coords.latitude,p.coords.longitude],a=Math.round(p.coords.accuracy||0),sp=gpsSpeed(p);if(a>0&&a>settings.maxAccuracy)return;if(lastPosition){const d=dist(lastPosition,cur);if(d>=3&&d<80)distanceMeters+=d}lastPosition=cur;points.push(cur);maxSpeed=Math.max(maxSpeed,sp);marker.setLatLng(cur);routeLine.setLatLngs(points);if(settings.autoCenter)map.setView(cur,map.getZoom(),{animate:false});$('distance').textContent=(distanceMeters/1000).toFixed(2)+' km';$('accuracy').textContent='±'+a+' m';$('speed').textContent=sp.toFixed(1)+' km/h';const hours=Math.max((Date.now()-startedAt)/3600000,1/3600);$('avgSpeed').textContent=(distanceMeters/1000/hours).toFixed(1)+' km/h';$('maxSpeed').textContent=maxSpeed.toFixed(1)+' km/h';if(followingRoute)updateFollowStatus(cur)}
function nearestRouteDistance(here,route){let near=Infinity;for(const pt of route.points||[])near=Math.min(near,dist(here,pt));return near}
function updateFollowStatus(here){const near=nearestRouteDistance(here,followingRoute);$('routeStatus').textContent=(followingRoute.name||'Route')+' · '+(near<35?'AUF ROUTE':'ABWEICHUNG '+Math.round(near)+' m');$('routeStatus').classList.remove('hidden')}
function gpsError(e){$('gpsStatus').textContent='GPS FEHLER';alert(e&&e.code===1?'Standortzugriff wurde verweigert. Bitte Standortzugriff für diese Website erlauben.':'GPS konnte nicht bestimmt werden. Bitte erneut versuchen.')}
function watch(cb){watchId=navigator.geolocation.watchPosition(cb,gpsError,{enableHighAccuracy:settings.highAccuracy,maximumAge:settings.trackingInterval,timeout:15000})}
function timer(){if(timerId)clearInterval(timerId);timerId=setInterval(()=>{if(startedAt)$('time').textContent=fmt(Date.now()-startedAt)},500)}
function prepareRide(){reset();startedAt=Date.now();$('gpsStatus').textContent='GPS AKTIV';show(ride)}
function startTracking(){if(!navigator.geolocation)return alert('GPS wird von diesem Browser nicht unterstützt.');followingRoute=null;$('followBanner').classList.add('hidden');prepareRide();navigator.geolocation.getCurrentPosition(p=>{initMap(p.coords.latitude,p.coords.longitude);routeLine.setLatLngs([]);if(savedRouteLine){map.removeLayer(savedRouteLine);savedRouteLine=null}setMarker(p.coords.latitude,p.coords.longitude);update(p);watch(update)},gpsError,{enableHighAccuracy:settings.highAccuracy,timeout:15000,maximumAge:0});timer()}
function follow(route){if(!route?.points||route.points.length<2)return alert('Diese Route enthält keine gültigen GPS-Punkte.');if(!navigator.geolocation)return alert('GPS wird von diesem Browser nicht unterstützt.');followingRoute=route;$('followBanner').classList.remove('hidden');prepareRide();navigator.geolocation.getCurrentPosition(p=>{initMap(p.coords.latitude,p.coords.longitude);routeLine.setLatLngs([]);if(savedRouteLine)map.removeLayer(savedRouteLine);savedRouteLine=L.polyline(route.points,{color:'#fff',weight:5,opacity:.55,dashArray:'8 9'}).addTo(map);setMarker(p.coords.latitude,p.coords.longitude);map.fitBounds(savedRouteLine.getBounds(),{padding:[24,24]});update(p);watch(update)},gpsError,{enableHighAccuracy:settings.highAccuracy,timeout:15000,maximumAge:0});timer()}
function centerOnUser(){if(!navigator.geolocation)return; navigator.geolocation.getCurrentPosition(p=>{if(!validPosition(p))return;initMap(p.coords.latitude,p.coords.longitude);if(!marker)setMarker(p.coords.latitude,p.coords.longitude);marker.setLatLng([p.coords.latitude,p.coords.longitude]);map.setView([p.coords.latitude,p.coords.longitude],17,{animate:true});$('gpsStatus').textContent='GPS AKTIV'},gpsError,{enableHighAccuracy:settings.highAccuracy,timeout:10000,maximumAge:0})}
function stop(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);if(timerId)clearInterval(timerId);watchId=null;timerId=null;if(points.length>=2&&!followingRoute&&settings.autoSave){const r=getRoutes();r.unshift({name:'Fahrt '+new Date().toLocaleDateString('de-DE'),distance:distanceMeters,duration:Date.now()-startedAt,points:[...points],created:Date.now(),maxSpeed});setRoutes(r)}if(savedRouteLine){map.removeLayer(savedRouteLine);savedRouteLine=null}followingRoute=null;$('followBanner').classList.add('hidden');$('routeStatus').classList.add('hidden');renderRoutes();show(routesScreen)}
function esc(t){return String(t).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderRoutes(){const list=$('routeList'),r=getRoutes();if(!r.length){list.innerHTML='<div class="route-empty">Noch keine Fahrten gespeichert.<br><br>Starte deine erste Fahrt! 🛴</div>';return}list.innerHTML=r.map((x,i)=>`<div class="route-item"><strong>${esc(x.name)}</strong><span>${(x.distance/1000).toFixed(2)} km · ${fmt(x.duration)}${x.maxSpeed?' · max. '+x.maxSpeed.toFixed(1)+' km/h':''}</span><div class="route-actions"><button data-follow="${i}">🧭 Route abfahren</button><button class="small-btn" data-rename="${i}">✏️</button><button class="small-btn delete" data-delete="${i}">🗑️</button></div></div>`).join('');list.querySelectorAll('[data-follow]').forEach(b=>b.onclick=()=>follow(r[+b.dataset.follow]));list.querySelectorAll('[data-rename]').forEach(b=>b.onclick=()=>{const x=r[+b.dataset.rename],n=prompt('Neuer Routenname:',x.name);if(n?.trim()){x.name=n.trim();setRoutes(r);renderRoutes()}});list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Diese Route wirklich löschen?')){r.splice(+b.dataset.delete,1);setRoutes(r);renderRoutes()}})}
function openSettings(){$('settingsPanel').classList.remove('hidden');$('autoCenter').checked=settings.autoCenter;$('highAccuracy').checked=settings.highAccuracy;$('autoSave').checked=settings.autoSave;$('trackingInterval').value=settings.trackingInterval;$('trackingIntervalValue').textContent=settings.trackingInterval+' ms';$('maxAccuracy').value=settings.maxAccuracy||100;$('versionInfo').textContent='E-TRACK V1.3'}
function closeSettings(){$('settingsPanel').classList.add('hidden')}
loadSettings();settings.maxAccuracy=settings.maxAccuracy||100;
$('startRide').onclick=startTracking;$('stopRide').onclick=stop;$('routes').onclick=()=>{renderRoutes();show(routesScreen)};$('backHome').onclick=()=>show(home);$('settings').onclick=openSettings;$('closeSettings').onclick=closeSettings;$('recenter').onclick=centerOnUser;$('autoCenter').onchange=e=>{settings.autoCenter=e.target.checked;saveSettings()};$('highAccuracy').onchange=e=>{settings.highAccuracy=e.target.checked;saveSettings()};$('autoSave').onchange=e=>{settings.autoSave=e.target.checked;saveSettings()};$('trackingInterval').oninput=e=>{settings.trackingInterval=Number(e.target.value);$('trackingIntervalValue').textContent=settings.trackingInterval+' ms';saveSettings()};$('maxAccuracy').oninput=e=>{settings.maxAccuracy=Number(e.target.value);$('maxAccuracyValue').textContent=settings.maxAccuracy+' m';saveSettings()};$('maxAccuracy').onchange=e=>{$('maxAccuracyValue').textContent=e.target.value+' m';saveSettings()};$('deleteData').onclick=()=>{if(confirm('Alle gespeicherten Routen löschen?')){localStorage.removeItem('e-track-routes');renderRoutes();closeSettings()}};$('resetSettings').onclick=()=>{settings={autoCenter:true,highAccuracy:true,trackingInterval:1000,autoSave:true,unit:'km',maxAccuracy:100};saveSettings();openSettings()};$('closeSettings').addEventListener('click',closeSettings);
