let map=null,marker=null,routeLine=null,savedRouteLine=null,watchId=null,timerId=null;
let points=[],startedAt=0,distanceMeters=0,maxSpeed=0,followingRoute=null,lastPosition=null,autoCenter=true,highAccuracy=true;
const $=id=>document.getElementById(id),home=$('homeScreen'),ride=$('rideScreen'),routesScreen=$('routesScreen');
function show(s){[home,ride,routesScreen].forEach(x=>x.classList.add('hidden'));s.classList.remove('hidden')}
function getRoutes(){try{return JSON.parse(localStorage.getItem('e-track-routes')||'[]')}catch{return[]}}
function setRoutes(r){localStorage.setItem('e-track-routes',JSON.stringify(r))}
function dist(a,b){const R=6371000,p=Math.PI/180,la=a[0]*p,lb=b[0]*p,dl=(b[0]-a[0])*p,do_= (b[1]-a[1])*p,x=Math.sin(dl/2)**2+Math.cos(la)*Math.cos(lb)*Math.sin(do_/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function fmt(ms){let t=Math.floor(ms/1000);return [Math.floor(t/3600),Math.floor(t%3600/60),t%60].map((v,i)=>i?String(v).padStart(2,'0'):String(v).padStart(2,'0')).join(':')}
function speed(p){return p.coords.speed!=null&&p.coords.speed>=0?p.coords.speed*3.6:0}
function reset(){points=[];distanceMeters=0;maxSpeed=0;lastPosition=null;$('time').textContent='00:00:00';$('distance').textContent='0.00 km';$('accuracy').textContent='…';$('speed').textContent='0 km/h';$('avgSpeed').textContent='0 km/h';$('maxSpeed').textContent='0 km/h'}
function initMap(lat,lon){if(!map){map=L.map('map',{zoomControl:false,preferCanvas:true}).setView([lat,lon],17);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);routeLine=L.polyline([],{color:'#ff3030',weight:5,opacity:.9}).addTo(map)}}
function setMarker(lat,lon){if(marker)map.removeLayer(marker);marker=L.circleMarker([lat,lon],{radius:8,color:'#fff',weight:3,fillColor:'#ff3030',fillOpacity:1}).addTo(map)}
function update(p){const cur=[p.coords.latitude,p.coords.longitude],a=Math.round(p.coords.accuracy||0),sp=speed(p);if(lastPosition){const d=dist(lastPosition,cur);if(d>=3&&d<80)distanceMeters+=d}lastPosition=cur;points.push(cur);maxSpeed=Math.max(maxSpeed,sp);marker.setLatLng(cur);routeLine.setLatLngs(points);if(autoCenter)map.setView(cur,map.getZoom(),{animate:false});$('distance').textContent=(distanceMeters/1000).toFixed(2)+' km';$('accuracy').textContent='±'+a+' m';$('speed').textContent=sp.toFixed(1)+' km/h';const hours=Math.max((Date.now()-startedAt)/3600000,1/3600);$('avgSpeed').textContent=(distanceMeters/1000/hours).toFixed(1)+' km/h';$('maxSpeed').textContent=maxSpeed.toFixed(1)+' km/h'}
function updateFollow(p){update(p);if(!followingRoute)return;let near=Infinity;const here=[p.coords.latitude,p.coords.longitude];for(const pt of followingRoute.points){near=Math.min(near,dist(here,pt))}const name=followingRoute.name||'Route';$('routeStatus').textContent=name+' · '+(near<35?'AUF ROUTE':'ABWEICHUNG '+Math.round(near)+' m');$('routeStatus').classList.remove('hidden')}
function gpsError(e){$('gpsStatus').textContent='GPS FEHLER';alert(e&&e.code===1?'Standortzugriff wurde verweigert. Bitte im Browser erlauben.':'GPS konnte nicht bestimmt werden. Bitte erneut versuchen.')}
function watch(cb){watchId=navigator.geolocation.watchPosition(cb,gpsError,{enableHighAccuracy:highAccuracy,maximumAge:1000,timeout:12000})}
function timer(){if(timerId)clearInterval(timerId);timerId=setInterval(()=>{if(startedAt)$('time').textContent=fmt(Date.now()-startedAt)},1000)}
function startTracking(){if(!navigator.geolocation)return alert('GPS wird von diesem Browser nicht unterstützt.');followingRoute=null;$('followBanner').classList.add('hidden');$('routeStatus').classList.add('hidden');reset();startedAt=Date.now();$('gpsStatus').textContent='GPS AKTIV';show(ride);navigator.geolocation.getCurrentPosition(p=>{initMap(p.coords.latitude,p.coords.longitude);routeLine.setLatLngs([]);if(savedRouteLine){map.removeLayer(savedRouteLine);savedRouteLine=null}setMarker(p.coords.latitude,p.coords.longitude);update(p);watch(update)},gpsError,{enableHighAccuracy:highAccuracy,timeout:12000,maximumAge:0});timer()}
function follow(route){if(!route?.points||route.points.length<2)return alert('Diese Route enthält keine gültigen GPS-Punkte.');if(!navigator.geolocation)return alert('GPS wird von diesem Browser nicht unterstützt.');followingRoute=route;reset();startedAt=Date.now();$('gpsStatus').textContent='GPS AKTIV';$('followBanner').classList.remove('hidden');show(ride);navigator.geolocation.getCurrentPosition(p=>{initMap(p.coords.latitude,p.coords.longitude);routeLine.setLatLngs([]);if(savedRouteLine)map.removeLayer(savedRouteLine);savedRouteLine=L.polyline(route.points,{color:'#fff',weight:5,opacity:.55,dashArray:'8 9'}).addTo(map);setMarker(p.coords.latitude,p.coords.longitude);map.fitBounds(savedRouteLine.getBounds(),{padding:[24,24]});updateFollow(p);watch(updateFollow)},gpsError,{enableHighAccuracy:highAccuracy,timeout:12000,maximumAge:0});timer()}
function stop(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);if(timerId)clearInterval(timerId);watchId=null;timerId=null;if(points.length>=2&&!followingRoute){const r=getRoutes();r.unshift({name:'Fahrt '+new Date().toLocaleDateString('de-DE'),distance:distanceMeters,duration:Date.now()-startedAt,points:[...points],created:Date.now(),maxSpeed});setRoutes(r)}if(savedRouteLine){map.removeLayer(savedRouteLine);savedRouteLine=null}followingRoute=null;$('followBanner').classList.add('hidden');$('routeStatus').classList.add('hidden');renderRoutes();show(routesScreen)}
function esc(t){return String(t).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderRoutes(){const list=$('routeList'),r=getRoutes();if(!r.length){list.innerHTML='<div class="route-empty">Noch keine Fahrten gespeichert.<br><br>Starte deine erste Fahrt! 🛴</div>';return}list.innerHTML=r.map((x,i)=>`<div class="route-item"><strong>${esc(x.name)}</strong><span>${(x.distance/1000).toFixed(2)} km · ${fmt(x.duration)}${x.maxSpeed?` · max. ${x.maxSpeed.toFixed(1)} km/h`:''}</span><div class="route-actions"><button data-follow="${i}">🧭 Route abfahren</button><button class="small-btn" data-rename="${i}">✏️</button><button class="small-btn delete" data-delete="${i}">🗑️</button></div></div>`).join('');list.querySelectorAll('[data-follow]').forEach(b=>b.onclick=()=>follow(r[+b.dataset.follow]));list.querySelectorAll('[data-rename]').forEach(b=>b.onclick=()=>{const x=r[+b.dataset.rename],n=prompt('Neuer Routenname:',x.name);if(n?.trim()){x.name=n.trim();setRoutes(r);renderRoutes()}});list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Diese Route wirklich löschen?')){r.splice(+b.dataset.delete,1);setRoutes(r);renderRoutes()}})}
function openSettings(){$('settingsPanel').classList.remove('hidden');$('autoCenter').checked=autoCenter;$('highAccuracy').checked=highAccuracy}
$('startRide').onclick=startTracking;$('stopRide').onclick=stop;$('routes').onclick=()=>{renderRoutes();show(routesScreen)};$('backHome').onclick=()=>show(home);$('settings').onclick=openSettings;$('closeSettings').onclick=()=>$('settingsPanel').classList.add('hidden');$('autoCenter').onchange=e=>autoCenter=e.target.checked;$('highAccuracy').onchange=e=>highAccuracy=e.target.checked;$('deleteData').onclick=()=>{if(confirm('Alle gespeicherten Routen löschen?')){localStorage.removeItem('e-track-routes');renderRoutes()}};
