// E-TRACK V3 — Google-Maps-inspired navigation UI + robust route rendering
(function(){
  const NOMINATIM='https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&q=';
  const OSRM='https://router.project-osrm.org/route/v1/driving/';
  let destination=null, navRoute=null, navSteps=[], stepIndex=0, navWatchId=null, rerouteBusy=false, lastRouteAt=0, destinationMarker=null, routeLayer=null;
  const esc=t=>String(t??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const fmtDist=m=>m>=1000?(m/1000).toFixed(m>=10000?0:1)+' km':Math.max(0,Math.round(m))+' m';
  const fmtTime=s=>{s=Math.max(0,Math.round(s));const h=Math.floor(s/3600),m=Math.floor(s%3600/60);return h?`${h} h ${m} min`:`${m} min`};
  const dir=(type,mod)=>{if(type==='arrive')return 'Ziel erreicht';if(type==='depart')return 'Losfahren';if(type==='roundabout'||type==='rotary')return 'Kreisverkehr';if(type==='merge')return 'Einfädeln';if(type==='fork')return (mod||'').includes('left')?'Links halten':'Rechts halten';if(type==='on ramp')return 'Auffahrt nehmen';if(type==='off ramp')return 'Ausfahrt nehmen';if((mod||'').includes('left'))return 'Links abbiegen';if((mod||'').includes('right'))return 'Rechts abbiegen';if(mod==='straight')return 'Geradeaus';return type==='uturn'?'Wenden':'Weiterfahren'};
  function current(){return new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:15000,maximumAge:0}))}
  async function search(q){const r=await fetch(NOMINATIM+encodeURIComponent(q),{headers:{Accept:'application/json'}});if(!r.ok)throw Error();return r.json()}
  async function route(from,to){const u=OSRM+from[1]+','+from[0]+';'+to[1]+','+to[0]+'?overview=full&geometries=geojson&steps=true';const r=await fetch(u);if(!r.ok)throw Error();const d=await r.json();if(d.code!=='Ok'||!d.routes?.[0])throw Error();return d.routes[0]}
  function panel(){const p=document.getElementById('navPanel');if(!p)return;p.className='nav-panel hidden';p.innerHTML=`<div class="nav-card-top"><div class="turn-icon" id="navIcon">➜</div><div class="nav-main"><span class="nav-eyebrow">ZIELFÜHRUNG</span><strong id="navInstruction">Route wird berechnet…</strong><span id="navStreet" class="nav-road">–</span></div><button id="navStop" class="nav-stop" aria-label="Navigation beenden">×</button></div><div class="nav-bottom"><span><b id="navRemaining">–</b><small>verbleibend</small></span><span><b id="navEta">–</b><small>ankunft</small></span><span><b id="navNext">–</b><small>nächster Schritt</small></span></div><div class="nav-progress"><i id="navProgress"></i></div>`;document.getElementById('navStop').onclick=stopNavigation}
  function destinationModal(){if(document.getElementById('destinationModal'))return;const m=document.createElement('div');m.id='destinationModal';m.className='modal hidden destination-modal';m.innerHTML=`<div class="modal-card"><div class="modal-head"><div><span class="nav-eyebrow">NAVIGATION</span><h2>Wohin?</h2></div><button class="back" id="closeDestination">×</button></div><div class="search-box"><span>⌖</span><input id="destinationQuery" autocomplete="off" placeholder="Adresse oder Ort suchen"><button id="destinationSearch">Suchen</button></div><div id="destResults" class="dest-results"><button class="dest-current" id="useCurrent"><span>◎</span><span><b>Standort verwenden</b><small>Deine aktuelle Position als Startpunkt</small></span></button><div class="dest-hint">Zum Beispiel: Bahnhof Tampere</div></div></div>`;document.body.appendChild(m);const close=()=>m.classList.add('hidden');document.getElementById('closeDestination').onclick=close;document.getElementById('destinationSearch').onclick=searchDest;document.getElementById('destinationQuery').onkeydown=e=>{if(e.key==='Enter')searchDest()};document.getElementById('useCurrent').onclick=()=>{document.getElementById('destinationQuery').value='';document.getElementById('destinationQuery').focus()}}
  async function searchDest(){const input=document.getElementById('destinationQuery'),q=input?.value.trim(),box=document.getElementById('destResults');if(!q)return;box.innerHTML='<div class="dest-loading">Suche läuft…</div>';try{const a=await search(q);if(!a.length){box.innerHTML='<div class="dest-hint">Kein Ziel gefunden. Bitte genauer suchen.</div>';return}box.innerHTML=a.map((x,i)=>`<button class="dest-result" data-i="${i}"><span class="result-pin">⌖</span><span><b>${esc(x.display_name.split(',')[0])}</b><small>${esc(x.display_name)}</small></span><span>›</span></button>`).join('');box.querySelectorAll('.dest-result').forEach((b,i)=>b.onclick=()=>{const x=a[i];document.getElementById('destinationModal').classList.add('hidden');startTo([+x.lat,+x.lon,x.display_name])})}catch{box.innerHTML='<div class="dest-hint">Suche fehlgeschlagen. Internetverbindung prüfen.</div>'}}
  function nearestGeometry(here){const g=navRoute?.geometry?.coordinates||[];let best=Infinity,idx=0;for(let i=0;i<g.length;i++){const d=dist(here,[g[i][1],g[i][0]]);if(d<best){best=d;idx=i}}return{d:best,idx}}
  function remainingDistance(here){const g=navRoute?.geometry?.coordinates||[];if(g.length<2)return navRoute?.distance||0;const n=nearestGeometry(here);let r=n.d;for(let i=n.idx;i<g.length-1;i++)r+=dist([g[i][1],g[i][0]],[g[i+1][1],g[i+1][0]]);return r}
  function stepDistance(h,s){const c=s?.maneuver?.location;return c?dist(h,[c[1],c[0]]):Infinity}
  function draw(r,here){navRoute=r;navSteps=(r.legs||[]).flatMap(l=>l.steps||[]).filter(s=>s.distance>0||s.maneuver?.type==='arrive');stepIndex=Math.max(0,navSteps.findIndex(s=>s.maneuver?.type!=='depart'));const p=document.getElementById('navPanel');if(p)p.classList.remove('hidden');if(routeLayer&&window.map){window.map.removeLayer(routeLayer)}if(window.map){routeLayer=L.geoJSON(r.geometry,{style:{color:'#ff303d',weight:8,opacity:1,lineCap:'round',lineJoin:'round'}}).addTo(window.map);routeLayer.bringToFront();window.savedRouteLine=routeLayer}if(destinationMarker&&window.map)window.map.removeLayer(destinationMarker);if(window.map){destinationMarker=L.circleMarker([destination[0],destination[1]],{radius:9,color:'#fff',weight:3,fillColor:'#ff3040',fillOpacity:1}).addTo(window.map);destinationMarker.bindTooltip('Ziel');window.map.fitBounds(routeLayer.getBounds(),{paddingTopLeft:[20,110],paddingBottomRight:[20,180]})}updateNav(here||window.__etrackNavPosition||null)}
  function updateNav(here){if(!navRoute)return;let s=navSteps[stepIndex];if(here){while(stepIndex<navSteps.length-1&&stepDistance(here,s)<22){stepIndex++;s=navSteps[stepIndex]}}const remaining=here?remainingDistance(here):navRoute.distance;const arrived=!!here&&dist(here,destination)<28;const p=document.getElementById('navPanel');if(!p)return;p.classList.toggle('arrived',arrived);const inst=document.getElementById('navInstruction');if(inst)inst.textContent=arrived?'Ziel erreicht':dir(s?.maneuver?.type,s?.maneuver?.modifier);const street=document.getElementById('navStreet');if(street)street.textContent=arrived?(destination[2]||'Ziel'):((s?.name||'').trim()||'Der Straße folgen');const rem=document.getElementById('navRemaining');if(rem)rem.textContent=fmtDist(arrived?0:remaining);const eta=document.getElementById('navEta');if(eta)eta.textContent=arrived?'JETZT':fmtTime(navRoute.duration*(remaining/Math.max(1,navRoute.distance)));const next=document.getElementById('navNext');if(next)next.textContent=navSteps[stepIndex+1]&&here?fmtDist(stepDistance(here,navSteps[stepIndex+1])):'–';const prog=document.getElementById('navProgress');if(prog)prog.style.width=Math.min(100,Math.max(0,(1-remaining/Math.max(1,navRoute.distance))*100))+'%';if(arrived)stopNavWatch()}
  async function startTo(to){if(!navigator.geolocation)return alert('Dieser Browser unterstützt kein GPS.');const b=document.getElementById('startDestination');if(b)b.disabled=true;try{const p=await current();destination=to;const r=await route([p.coords.latitude,p.coords.longitude],to);if(window.startTracking)window.startTracking();setTimeout(()=>{window.__etrackNavPosition=[p.coords.latitude,p.coords.longitude];draw(r,window.__etrackNavPosition);startNavWatch()},700)}catch{alert('Zielführung konnte nicht berechnet werden. Prüfe Standort und Internet.')}finally{if(b)b.disabled=false}}
  function startNavWatch(){stopNavWatch();navWatchId=navigator.geolocation.watchPosition(async p=>{if(!p?.coords)return;const here=[p.coords.latitude,p.coords.longitude];window.__etrackNavPosition=here;updateNav(here);if(navRoute&&!rerouteBusy&&Date.now()-lastRouteAt>12000&&nearestGeometry(here).d>85){rerouteBusy=true;try{const r=await route(here,destination);lastRouteAt=Date.now();draw(r,here)}catch{}finally{rerouteBusy=false}}},{enableHighAccuracy:true,maximumAge:0,timeout:20000});lastRouteAt=Date.now()}
  function stopNavWatch(){if(navWatchId!==null)navigator.geolocation.clearWatch(navWatchId);navWatchId=null}
  function clearNav(){stopNavWatch();destination=null;navRoute=null;navSteps=[];stepIndex=0;window.__etrackNavPosition=null;if(destinationMarker&&window.map){window.map.removeLayer(destinationMarker);destinationMarker=null}if(routeLayer&&window.map){window.map.removeLayer(routeLayer);routeLayer=null}window.savedRouteLine=null;const p=document.getElementById('navPanel');if(p)p.classList.add('hidden')}
  function stopNavigation(){clearNav();if(typeof window.stop==='function')window.stop()}
  function openDestination(){destinationModal();const m=document.getElementById('destinationModal');m.classList.remove('hidden');const i=document.getElementById('destinationQuery');i.value='';setTimeout(()=>i.focus(),80)}
  function patchHome(){const b=document.getElementById('startDestination');if(b){b.onclick=openDestination;b.textContent='⌖  Ziel eingeben'}}
  function patchRoutes(){document.querySelectorAll('#routeList [data-follow]').forEach(b=>{b.textContent='⌖  Als Ziel nutzen';b.onclick=()=>{const r=JSON.parse(localStorage.getItem('e-track-routes')||'[]')[+b.dataset.follow];const last=r?.points?.[r.points.length-1];if(last)startTo([last[0],last[1],r.name||'Gespeichertes Ziel'])}})}
  panel();destinationModal();patchHome();const oldRender=window.renderRoutes;window.renderRoutes=function(){if(oldRender)oldRender();setTimeout(patchRoutes,0)};document.addEventListener('DOMContentLoaded',()=>{panel();destinationModal();patchHome()});
  const finish=document.getElementById('stopRide'),baseStop=window.stop;if(finish&&baseStop)finish.onclick=()=>{clearNav();baseStop()};window.addEventListener('beforeunload',stopNavWatch);
})();
